version: "3.8"

services:
  backend:
    build: .
    container_name: fastapi_app
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always

  db:
    image: postgres:15
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7
    container_name: redis_cache
    env_file:
      - .env
    ports:
      - "6379:6379"
    restart: always

volumes:
  postgres_data:
