"""Initial tables

Revision ID: bab176ad77be
Revises: 
Create Date: 2025-03-13 16:41:08.046751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bab176ad77be'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('hashed_password', sa.String(length=60), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_index(op.f('id_users_id'), 'users', ['id'], unique=True)
    op.create_index(op.f('id_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_table('activities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('activity_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_activities_user_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activities'))
    )
    op.create_index(op.f('id_activities_id'), 'activities', ['id'], unique=True)
    op.create_table('activity_types',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.Column('color_asigned', sa.String(length=7), nullable=False),
    sa.Column('activity_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], name=op.f('fk_activity_types_activity_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_types'))
    )
    op.create_index(op.f('id_activity_types_id'), 'activity_types', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('id_activity_types_id'), table_name='activity_types')
    op.drop_table('activity_types')
    op.drop_index(op.f('id_activities_id'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('id_users_is_active'), table_name='users')
    op.drop_index(op.f('id_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
